@ImageWorker.Server_HostAddress = https://localhost:7146

GET {{ImageWorker.Server_HostAddress}}/api/dataitems
Accept: application/json
###

GET {{ImageWorker.Server_HostAddress}}/api/dataitems/filename
Accept: application/json
###

POST {{ImageWorker.Server_HostAddress}}/api/dataitems
Accept: application/json
Content-Type: application/json

{
   "guId": "2108B25C-89F3-4F26-B764-A2F1A229DCCB",
   "fileName": "filename2",
   "fileData": "ZmlsZWRhdGE="
}
###

DELETE  {{ImageWorker.Server_HostAddress}}/api/dataitems/avatar.png
Accept: application/json
###
